/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Degen } from "./Degen";
export type { GGGAME } from "./GGGAME";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { Degen__factory } from "./factories/Degen__factory";
export { GGGAME__factory } from "./factories/GGGAME__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
