/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Degen__factory } from "./Degen__factory";
export { GGGAME__factory } from "./GGGAME__factory";
export { IERC20__factory } from "./IERC20__factory";
